version: 0.2
run-as: root
env:
  secrets-manager:
    DB_PASSWORD: laravel-app:DB_PASSWORD
    DB_HOST: laravel-app:DB_HOST
phases:
  install:
    runtime-versions: 
      php: 7.3
    commands:
      - echo Installing...
  pre_build:
    commands:
      - mv .env.example .env
      - sed -i "s|APP_URL=http://127.0.0.1:8000/|APP_URL=https://laravel.labs.squareops.in|" .env
      - sed -i "s|DB_HOST=127.0.0.1|DB_HOST=$DB_HOST|" .env
      - sed -i "s|DB_PASSWORD=|DB_PASSWORD=$DB_PASSWORD|" .env
  build:
    commands:
      - composer update
      - composer install
      - php artisan key:generate
      - php artisan storage:link
artifacts:
  files:
    - "**/*"
    - echo Uploaded Artifacts
