version: 0.2
run-as: root
env:
  secrets-manager:
    DB_PASSWORD: laravel-app:DB_PASSWORD
phases:
  install:
    runtime-versions: 
      php: 7.3
    commands:
      - echo Installing...
  pre_build:
    commands:
      - mv .env.example .env
      - sed -i "s|APP_URL=http://127.0.0.1:8000/|APP_URL=http://laravel.labs.squareops.in|" .env
      - sed -i "s|DB_HOST=127.0.0.1|DB_HOST=prod-laravel-mysql.cluster-c5zbpa0be4xa.us-east-1.rds.amazonaws.com|" .env
      - sed -i "s|DB_PASSWORD=|DB_PASSWORD=admin123|" .env
  build:
    commands:
      - composer update
      - composer install
artifacts:
  files:
    - "**/*"
    - echo Uploaded Artifacts
